---
# Source: project-atlas/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: "project-atlas"
---
# Source: project-atlas/templates/backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: project-atlas
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
# Source: project-atlas/templates/frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: project-atlas
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
# Source: project-atlas/templates/backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: project-atlas
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "docker.io/xgalvanize/project-atlas-backend:latest"
          ports:
            - containerPort: 8000
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
---
# Source: project-atlas/templates/frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: project-atlas
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "docker.io/xgalvanize/project-atlas-frontend:latest"
          ports:
            - containerPort: 80
---
# Source: project-atlas/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: project-atlas-ingress
  namespace: project-atlas
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: atlas.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
    - host: api.atlas.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8000
