# Generated by Django 6.0.1 on 2026-01-29 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_actor_name_remove_actor_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='user',
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
    ]
