# Generated by Django 6.0.1 on 2026-01-30 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_actor_user_delete_action_delete_actor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='created_at',
            new_name='createdAt',
        ),
    ]
