# Generated by Django 6.0.1 on 2026-01-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(help_text='Free-form category (assign, deliver, deploy, inspect, etc.)', max_length=50)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('context', models.JSONField(blank=True, help_text='Arbitrary structured data for this action', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
