# Generated by Django 6.0.1 on 2026-01-31 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_created_at_project_createdat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='createdAt',
            new_name='created_at',
        ),
    ]
