# Generated by Django 6.0.1 on 2026-01-22 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='projects.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='action',
            name='context',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
