# Generated by Django 6.0.1 on 2026-01-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_action_project_alter_action_action_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='context',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
