# Generated by Django 6.0.1 on 2026-01-26 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_action_actor_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='projects.task')),
            ],
        ),
    ]
