# Generated by Django 6.0.1 on 2026-01-30 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='created_by',
            new_name='createdBy',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='created_by',
            new_name='createdBy',
        ),
    ]
