# Generated by Django 6.0.1 on 2026-01-31 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_rename_created_at_action_createdat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='createdBy',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='createdBy',
            new_name='created_by',
        ),
    ]
